### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by nouryehia** [AlbertXDing/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
   - VSCode link should be embedded
   - Account look up link should be embedded
- [x] All relevant code examples written with backticks (```)
   - `ssh` command should be in backticks 
   - Anything that follows "Type" should be in backticks as it is technically a command
   - All `scp` commands should be in backticks
   - the whole WhereAmI class should be in triple backticks
   - `ssh-keygen` instances should be in backticks
   - `mkdir` should be in backticks
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
   - not included
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:

I would also recommend putting file names in backticks.
--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by AlbertXDing** [comment]
What is meant by "last example counts keystrokes and shows how to run remotely saving time"? 

Just to clarify, is the link to our feedback and our changed post all that needs to be sent in our regrade request?

**Comment by nouryehia** [comment]
What is meant by this is that you should count (approximately) the number of times you hit a key / click the mouse before and after your optimizations to see how much time you actually saved.

And  for regrade requests, you should submit the link to this issue and the link to your website
